#           ______    __                     _____                          _             __    ____
#          /_  __/   / /_   __  __   _____  / ___/    ____   ___   _____   (_)  ____ _   / /   / __ \   _____  ____     ____    _____
#           / /     / __ \ / / / /  / ___/  \__ \    / __ \ / _ \ / ___/  / /  / __ `/  / /   / / / /  / ___/ / __ \   / __ \  / ___/
#          / /     / / / // /_/ /  / /     ___/ /   / /_/ //  __// /__   / /  / /_/ /  / /   / /_/ /  / /    / /_/ /  / /_/ / (__  )
#         /_/     /_/ /_/ \____/  /_/     /____/   / ____/ \___/ \___/  /_/   \____/  /_/   /_____/  /_/     \____/  / ____/ /____/
#                                                 /_/                                                               /_/
CREEPER:
  DROP_DEFAULT_ITEM: false
  COMMAND: givecaixa 1 {QUANTIDADE} {PLAYER}
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
SKELETON:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
SPIDER:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
ZOMBIE:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
SLIME:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
GHAST:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
PIG_ZOMBIE:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
ENDERMAN:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
CAVE_SPIDER:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
SILVERFISH:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
BLAZE:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
MAGMA_CUBE:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
BAT:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
WITCH:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
ENDERMITE:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
GUARDIAN:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
PIG:
  DROP_DEFAULT_ITEM: true
  COMMAND: givecaixa 5 1 {PLAYER}
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
SHEEP:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
COW:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
CHICKEN:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
SQUID:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
WOLF:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
MUSHROOM_COW:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
OCELOT:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
HORSE:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
RABBIT:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
VILLAGER:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
WHITER:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
IRON_GOLEM:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
SNOWMAN:
  DROP_DEFAULT_ITEM: true
  COMMAND: ''
  CHANCE: 100
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2
WHITER_SKULL:
  DROP_DEFAULT_ITEM: true
  COMMAND: givecaixa {PLAYER} 5 1
  CHANCE: 1
  MESSAGE: '&aVoce ganhou um item raro com apenas {CHANCE}% de chance.'
  QUANT_MIN: 1
  QUANT_MAX: 2